src/main/default/objects/OutOfOfficeRequest_OOOR__c/OutOfOfficeRequest_OOOR__c.object-meta.xml
<CustomObject>
    <description
  >This object is going to be used to log out of the office records for users. These records are going to be read by an Apex class, which will then re-assign records based on the custom metadata settings defined in OutOfTheOfficeSettings__mdt.
Demen S. 27th Oct 2020.</description>
    <label>Out of Office Request</label>
    <nameField>
        <displayFormat>OOOR-{0000}</displayFormat>
        <label>Out of Office Reuest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Out of Office Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/BackupUser_OOOR__c.field-meta.xml
<CustomField>
    <fullName>BackupUser_OOOR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >Records ob defined Objects in OutOfTheOfficeSettingsOOOR__mdt are going to be re-assigned to this user.
Demen S. 27th Oct 2020.</description>
    <label>Backup User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BackupUser_OutOfOfficeRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/EndDate_OOOR__c.field-meta.xml
<CustomField>
    <fullName>EndDate_OOOR__c</fullName>
    <description
  >This is the ed date of the OOO. Based on this date, records are going to be stopped to be re-assigned.
Demen S. 27th Oct 2020.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/PersonTakingTimeOff_OOOR__c.field-meta.xml
<CustomField>
    <fullName>PersonTakingTimeOff_OOOR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >Records ob defined Objects in OutOfTheOfficeSettingsOOOR__mdt are going to be re-assigned from this owner.
Demen S. 27th Oct 2020.</description>
    <label>Person taking Time Off</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PersonTakingTimeOff_OutOfOfficeRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/StartDate_OOOR__c.field-meta.xml
<CustomField>
    <fullName>StartDate_OOOR__c</fullName>
    <description
  >This is the start date of the OOO. Based on this date, records are going to be re-assigned.
Demen S. 27th Oct 2020.</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/Status_OOOR__c.field-meta.xml
<CustomField>
    <fullName>Status_OOOR__c</fullName>
    <defaultValue>&quot;Approved&quot;</defaultValue>
    <description
  >This field is going to be update by the approval process Backup_Approval. Only Approved out of office records are going to be considered by the APEX class oooh_OutOfTheOfficeBatchable.
Demen S. 19th 2020.</description>
    <inlineHelpText
  >This status field is going to be updated automatically by the outcome of the approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Task/recordTypes/TESTRECORDTYPE_OOOR.recordType-meta.xml
<RecordType>
    <fullName>TESTRECORDTYPE_OOOR</fullName>
    <active>true</active>
    <description
  >DO NOT DELETE. This record type is needed for testing the Out of Office Request Code. Demen S. 27th Jun 2021</description>
    <label>TESTRECORDTYPE_OOOR</label>
</RecordType>

src/main/default/classes/TestDataFactoryOOOR.cls
/*
Author: Demen Selcan
E-Mail: dselcan@salesforce.com
Last Updated: 27th Jun 2021
*/

@isTest
public class TestDataFactoryOOOR {
  public static List<Case> getCases(
    String Subject,
    String Origin,
    Integer NumberOfRecords
  ) {
    List<Case> cases = new List<Case>();
    for (Integer i = 0; i <= NumberOfRecords; i++) {
      Case cs = new Case();
      cs.Subject = Subject + i;
      cs.Origin = Origin;
      cases.add(cs);
      i++;
    }
    return cases;
  }

  public static List<Task> getTasks(
    String Subject,
    String Status,
    String Priority,
    Boolean IsReminderSet,
    Integer NumberOfRecords
  ) {
    List<Task> tasks = new List<Task>();
    Id taskRecordTypeId = [
      SELECT Id, DeveloperName
      FROM RecordType
      WHERE SobjectType = 'Task' AND DeveloperName = 'TESTRECORDTYPE_OOOR'
      LIMIT 1
    ]
    .Id;
    for (Integer i = 0; i <= NumberOfRecords; i++) {
      Task tsk = new Task();
      tsk.Subject = Subject + i;
      tsk.Status = Status;
      tsk.IsReminderSet = IsReminderSet;
      tsk.RecordTypeId = taskRecordTypeId;
      tsk.Priority = Priority;
      tasks.add(tsk);
      i++;
    }
    return tasks;
  }

  public static OutOfOfficeRequest_OOOR__c getOutOfOfficeRequestRecords(
    Id PersonTakingTimeOff,
    Id BackUpUser,
    String Status,
    Date StartDate,
    Date EndDate
  ) {
    OutOfOfficeRequest_OOOR__c oooRequest = new OutOfOfficeRequest_OOOR__c();
    oooRequest.PersonTakingTimeOff_OOOR__c = PersonTakingTimeOff;
    oooRequest.Status_OOOR__c = Status;
    oooRequest.BackupUser_OOOR__c = BackUpUser;
    oooRequest.StartDate_OOOR__c = StartDate;
    oooRequest.EndDate_OOOR__c = EndDate;

    return oooRequest;
  }
  public static User generateUser(
    String profileName,
    String lastName,
    String email,
    String userName,
    String companyName,
    String title,
    String alias
  ) {
    User u = new User(
      ProfileId = [SELECT Id FROM Profile WHERE Name = :profileName]
      .Id,
      LastName = lastName,
      Email = email,
      Username = userName,
      CompanyName = companyName,
      Title = title,
      Alias = alias,
      TimeZoneSidKey = 'America/Los_Angeles',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US'
    );
    return u;
  }
}