src/main/default/objects/OutOfOfficeRequest_OOOR__c/OutOfOfficeRequest_OOOR__c.object-meta.xml
<CustomObject>
    <description
  >This object is going to be used to log out of the office records for users. These records are going to be read by an Apex class, which will then re-assign records based on the custom metadata settings defined in OutOfTheOfficeSettings__mdt.
Demen S. 27th Oct 2020.</description>
    <label>Out of Office Request</label>
    <nameField>
        <displayFormat>OOOR-{0000}</displayFormat>
        <label>Out of Office Reuest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Out of Office Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/BackupUser_OOOR__c.field-meta.xml
<CustomField>
    <fullName>BackupUser_OOOR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >Records ob defined Objects in OutOfTheOfficeSettingsOOOR__mdt are going to be re-assigned to this user.
Demen S. 27th Oct 2020.</description>
    <label>Backup User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BackupUser_OutOfOfficeRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/EndDate_OOOR__c.field-meta.xml
<CustomField>
    <fullName>EndDate_OOOR__c</fullName>
    <description
  >This is the ed date of the OOO. Based on this date, records are going to be stopped to be re-assigned.
Demen S. 27th Oct 2020.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/PersonTakingTimeOff_OOOR__c.field-meta.xml
<CustomField>
    <fullName>PersonTakingTimeOff_OOOR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >Records ob defined Objects in OutOfTheOfficeSettingsOOOR__mdt are going to be re-assigned from this owner.
Demen S. 27th Oct 2020.</description>
    <label>Person taking Time Off</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PersonTakingTimeOff_OutOfOfficeRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/StartDate_OOOR__c.field-meta.xml
<CustomField>
    <fullName>StartDate_OOOR__c</fullName>
    <description
  >This is the start date of the OOO. Based on this date, records are going to be re-assigned.
Demen S. 27th Oct 2020.</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/Status_OOOR__c.field-meta.xml
<CustomField>
    <fullName>Status_OOOR__c</fullName>
    <defaultValue>&quot;Approved&quot;</defaultValue>
    <description
  >This field is going to be update by the approval process Backup_Approval. Only Approved out of office records are going to be considered by the APEX class oooh_OutOfTheOfficeBatchable.
Demen S. 19th 2020.</description>
    <inlineHelpText
  >This status field is going to be updated automatically by the outcome of the approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/OutOfTheOfficeSettings_OOOR__mdt.object-meta.xml
<CustomObject>
    <description
  >This Custom Metadata Object lets admins/users with required permission configure global settings for our OOO Handler. Example: What objects our handler should consider, if there should be a post to the record feed (requires chatter to be enabled) or if the record is active or not.
Demen S. 27th Oct 2020.</description>
    <label>Out of The Office Setting</label>
    <pluralLabel>Out of The Office Settings</pluralLabel>
</CustomObject>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/Active_OOOR__c.field-meta.xml
<CustomField>
    <fullName>Active_OOOR__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >This field is being read by the oooh Apex Class and the corresponding object will be considered if this is set to true. It will be ignored if false.
Demen S. 27th Oct 2020.</description>
    <inlineHelpText
  >This checkbox defines if your object will be considered in the next oooh run or not.</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/FeedPost_OOOR__c.field-meta.xml
<CustomField>
    <fullName>FeedPost_OOOR__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >This field defines if a feed post will be stamped or not. Please make sure that Chatter is enabled if feed posts are turned on.
Demen S. 27th Oct 2020.</description>
    <inlineHelpText
  >If checked, you must provide a Feed Post Message. Please note, Chatter is required for Feed Posts.</inlineHelpText>
    <label>Feed Post?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/FeedPostMessage_OOOR__c.field-meta.xml
<CustomField>
    <fullName>FeedPostMessage_OOOR__c</fullName>
    <defaultValue
  >&quot;This record has been re-assigned, as the original owner is OOO.&quot;</defaultValue>
    <description
  >This content of this field will be used to stamp the message on the re-assigned record.
Demen S. 27th Oct. 2020.</description>
    <inlineHelpText
  >Please add your Post Message. Please note, Chatter is required for feed messages.</inlineHelpText>
    <label>Feed Post Message</label>
    <type>TextArea</type>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/FieldName_OOOR__c.field-meta.xml
<CustomField>
    <fullName>FieldName_OOOR__c</fullName>
    <description
  >This field will be used to build the query in the Apex Class oooh_OutOfTheOfficeBatchable.
Demen S. 2nd Mar 2021</description>
    <label>Field Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/ObjectAPIName_OOOR__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName_OOOR__c</fullName>
    <description
  >This field will be used by an Apex Class, which will re-assign records on the above mentioned object, based on the created out of office logs.
Demen S. 27th Oct 2020.</description>
    <inlineHelpText
  >Please add you Object API Name e.g. Case or Custom_Object_OOOR__c</inlineHelpText>
    <label>Object API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/QueryFilter_OOOR__c.field-meta.xml
<CustomField>
    <fullName>QueryFilter_OOOR__c</fullName>
    <description
  >This field contains the query filter for example: ....WHERE Name = &apos;Sandy&apos;</description>
    <inlineHelpText
  >Values are being escaped. Therefore, do not add any quotation marks Example: (Good): Completed (Bad): &apos;Completed&apos;.</inlineHelpText>
    <label>Query Filter</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/QueryParameter_OOOR__c.field-meta.xml
<CustomField>
    <fullName>QueryParameter_OOOR__c</fullName>
    <description
  >This field will be used to build the query in the Apex Class oooh_OutOfTheOfficeBatchable.
Demen S. 2nd Mar 2021</description>
    <label>Query Parameter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
                <default>true</default>
                <label>=</label>
            </value>
            <value>
                <fullName>!=</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>=&lt;</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/RecordType_OOOR__c.field-meta.xml
<CustomField>
    <fullName>RecordType_OOOR__c</fullName>
    <description
  >This field can be used to restrict the query to a certain record type.</description>
    <inlineHelpText>Please enter your record type API Name here with no quotes.
Example - Correct: Business_Case NOT Correct &apos;Business Case&apos;</inlineHelpText>
    <label>Record Type API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/OutOfOfficeBatchableOOOR.cls
/*
Author: Demen Selcan
E-Mail: dselcan@salesforce.com
Last Updated: 27th Jun 2021
*/

public with sharing class OutOfOfficeBatchableOOOR implements Database.Batchable<SObject>, Database.Stateful {
  private Integer settingsIndex = 0;
  // Doesn't count against governors as we are querying CMDT. This helps to reference this list across all methods.
  @testVisible
  public static List<OutOfTheOfficeSettings_OOOR__mdt> querySettings {
    get {
      if (querySettings == null) {
        querySettings = [
          SELECT
            ObjectAPIName_OOOR__c,
            Active_OOOR__c,
            FeedPost_OOOR__c,
            FeedPostMessage_OOOR__c,
            FieldName_OOOR__c,
            QueryParameter_OOOR__c,
            QueryFilter_OOOR__c,
            RecordType_OOOR__c
          FROM OutOfTheOfficeSettings_OOOR__mdt
          WHERE Active_OOOR__c = TRUE
        ];
      }
      return querySettings;
    }
    set;
  }

  public List<SObject> start(Database.BatchableContext BC) {
    OutOfOfficeOOOR outOfOfficeClass = new OutOfOfficeOOOR();
    //Get out of office records from OutOfOfficeRequest_OOOR__c and return results. This contains all users that are OOO and the corresponding dates
    Set<Id> userIdsCurrentlyOOO = new Set<Id>();
    for (OutOfOfficeRequest_OOOR__c oooRecord : [
      SELECT Id, BackupUser_OOOR__c, PersonTakingTimeOff_OOOR__c, Status_OOOR__c
      FROM OutOfOfficeRequest_OOOR__c
      WHERE
        StartDate_OOOR__c <= TODAY
        AND EndDate_OOOR__c >= TODAY
        AND Status_OOOR__c = 'Approved'
    ]) {
      userIdsCurrentlyOOO.add(oooRecord.PersonTakingTimeOff_OOOR__c);
    }

    // Call outOfOfficeClass.buildWhereClause method which checks the field types to query and applies SOQL Injection safety methods.
    String selectStatement =
      'SELECT Id, OwnerId FROM ' +
      querySettings[settingsIndex].ObjectAPIName_OOOR__c;

    String whereClause = outOfOfficeClass.buildWhereClause(
      ' WHERE ',
      querySettings[settingsIndex].ObjectAPIName_OOOR__c,
      querySettings[settingsIndex].FieldName_OOOR__c,
      querySettings[settingsIndex].QueryParameter_OOOR__c,
      querySettings[settingsIndex].QueryFilter_OOOR__c,
      querySettings[settingsIndex].RecordType_OOOR__c
    );

    // Build the where clause which is being passed to execution method eventually.
    String scope =
      selectStatement +
      whereClause +
      ' AND OwnerId IN : ' +
      'userIdsCurrentlyOOO';

    // calling a sanitizing function which checks if the object and field name are valid and validates CRUD, too.
    if (
      !(outOfOfficeClass.isSafeFieldAndObject(
        querySettings[settingsIndex].ObjectAPIName_OOOR__c,
        querySettings[settingsIndex].FieldName_OOOR__c
      ))
    ) {
      return null;
    } else if (
      // calling a sanitizing function which checks if the record type name is valid.
      querySettings[settingsIndex].RecordType_OOOR__c != null &&
      !(outOfOfficeClass.isSafeRecordType(
        querySettings[settingsIndex].ObjectAPIName_OOOR__c,
        querySettings[settingsIndex].RecordType_OOOR__c
      ))
    ) {
      return null;
    } else {
      System.debug('What is the query returned by start method? ' + scope);
      return Database.query(scope);
    }
  }

  public void execute(Database.BatchableContext BC, List<SObject> scope) {
    OutOfOfficeOOOR outOfOfficeClass = new OutOfOfficeOOOR();
    List<SObject> recordsToBeUpdated = outOfOfficeClass.getRecordsToBeReassigned(
      scope
    );

    List<SObject> recordFeedPosts = outOfOfficeClass.getFeedPosts(
      scope,
      querySettings
    );

    // update records with backup user and insert Feedpost if enabled
    if (recordsToBeUpdated.size() > 0) {
      update recordsToBeUpdated;
      if (recordFeedPosts.size() > 0) {
        insert recordFeedPosts;
      }
    }
  }

  public void finish(Database.BatchableContext BC) {
    if (settingsIndex < querySettings.size() - 1) {
      settingsIndex++;
      Database.executeBatch(this);
    }
  }
}