src/main/default/objects/OutOfOfficeRequest_OOOR__c/OutOfOfficeRequest_OOOR__c.object-meta.xml
<CustomObject>
    <description
  >This object is going to be used to log out of the office records for users. These records are going to be read by an Apex class, which will then re-assign records based on the custom metadata settings defined in OutOfTheOfficeSettings__mdt.
Demen S. 27th Oct 2020.</description>
    <label>Out of Office Request</label>
    <nameField>
        <displayFormat>OOOR-{0000}</displayFormat>
        <label>Out of Office Reuest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Out of Office Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/BackupUser_OOOR__c.field-meta.xml
<CustomField>
    <fullName>BackupUser_OOOR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >Records ob defined Objects in OutOfTheOfficeSettingsOOOR__mdt are going to be re-assigned to this user.
Demen S. 27th Oct 2020.</description>
    <label>Backup User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BackupUser_OutOfOfficeRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/EndDate_OOOR__c.field-meta.xml
<CustomField>
    <fullName>EndDate_OOOR__c</fullName>
    <description
  >This is the ed date of the OOO. Based on this date, records are going to be stopped to be re-assigned.
Demen S. 27th Oct 2020.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/PersonTakingTimeOff_OOOR__c.field-meta.xml
<CustomField>
    <fullName>PersonTakingTimeOff_OOOR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >Records ob defined Objects in OutOfTheOfficeSettingsOOOR__mdt are going to be re-assigned from this owner.
Demen S. 27th Oct 2020.</description>
    <label>Person taking Time Off</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PersonTakingTimeOff_OutOfOfficeRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/StartDate_OOOR__c.field-meta.xml
<CustomField>
    <fullName>StartDate_OOOR__c</fullName>
    <description
  >This is the start date of the OOO. Based on this date, records are going to be re-assigned.
Demen S. 27th Oct 2020.</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/main/default/objects/OutOfOfficeRequest_OOOR__c/fields/Status_OOOR__c.field-meta.xml
<CustomField>
    <fullName>Status_OOOR__c</fullName>
    <defaultValue>&quot;Approved&quot;</defaultValue>
    <description
  >This field is going to be update by the approval process Backup_Approval. Only Approved out of office records are going to be considered by the APEX class oooh_OutOfTheOfficeBatchable.
Demen S. 19th 2020.</description>
    <inlineHelpText
  >This status field is going to be updated automatically by the outcome of the approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/OutOfTheOfficeSettings_OOOR__mdt.object-meta.xml
<CustomObject>
    <description
  >This Custom Metadata Object lets admins/users with required permission configure global settings for our OOO Handler. Example: What objects our handler should consider, if there should be a post to the record feed (requires chatter to be enabled) or if the record is active or not.
Demen S. 27th Oct 2020.</description>
    <label>Out of The Office Setting</label>
    <pluralLabel>Out of The Office Settings</pluralLabel>
</CustomObject>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/FeedPost_OOOR__c.field-meta.xml
<CustomField>
    <fullName>FeedPost_OOOR__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >This field defines if a feed post will be stamped or not. Please make sure that Chatter is enabled if feed posts are turned on.
Demen S. 27th Oct 2020.</description>
    <inlineHelpText
  >If checked, you must provide a Feed Post Message. Please note, Chatter is required for Feed Posts.</inlineHelpText>
    <label>Feed Post?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/FeedPostMessage_OOOR__c.field-meta.xml
<CustomField>
    <fullName>FeedPostMessage_OOOR__c</fullName>
    <defaultValue
  >&quot;This record has been re-assigned, as the original owner is OOO.&quot;</defaultValue>
    <description
  >This content of this field will be used to stamp the message on the re-assigned record.
Demen S. 27th Oct. 2020.</description>
    <inlineHelpText
  >Please add your Post Message. Please note, Chatter is required for feed messages.</inlineHelpText>
    <label>Feed Post Message</label>
    <type>TextArea</type>
</CustomField>

src/main/default/objects/OutOfTheOfficeSettings_OOOR__mdt/fields/ObjectAPIName_OOOR__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName_OOOR__c</fullName>
    <description
  >This field will be used by an Apex Class, which will re-assign records on the above mentioned object, based on the created out of office logs.
Demen S. 27th Oct 2020.</description>
    <inlineHelpText
  >Please add you Object API Name e.g. Case or Custom_Object_OOOR__c</inlineHelpText>
    <label>Object API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/OutOfOfficeOOOR.cls
/*
Author: Demen Selcan
E-Mail: dselcan@salesforce.com
Last Updated: 27th Jun 2021
*/

public with sharing class OutOfOfficeOOOR {
  // sanitizing method to check if field and object are valid and accessible
  public boolean isSafeFieldAndObject(String objName, String fieldName) {
    Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
    SObjectType myObj = schemaMap.get(objName);
    if (myObj.getDescribe().isAccessible()) {
      SObjectField myField = myObj.getDescribe().fields.getMap().get(fieldName);
      if (myField.getDescribe().isAccessible()) {
        return true;
      }
    }
    System.debug(
      'Please check your field entry in OutOfTheOfficeSettings_OOOR__mdt. Here is what you have entered: ' +
      myObj.getDescribe().fields.getMap().get(fieldName) +
      ' There might be a typo, or your user may not have FLS permission for that.'
    );
    return false;
  }

  // sanitizing method to check if record type is valid and accessible
  public boolean isSafeRecordType(String objName, String recordTypeAPIName) {
    Boolean isRecordTypeAvailable = false;
    Map<String, Schema.RecordTypeInfo> recordTypeMap = Schema.getGlobalDescribe()
      .get(objName)
      .getDescribe()
      .getRecordTypeInfosByDeveloperName();
    if (recordTypeMap.get(recordTypeAPIName).isActive()) {
      return true;
    }
    System.debug(
      'Please check your record type for objecttype: ' +
      objName +
      ' and record type entry ' +
      recordTypeAPIName +
      ' Is Record Type Active? ' +
      recordTypeMap.get(recordTypeAPIName).isActive() +
      '. There might be a typo or it is inactive.'
    );
    return false;
  }

  // method to build the where clause for dynamic soql. It checks if the field is a string or not.
  // If string it uses the escapeSingleQuotes method. If not String, the valueOf method is applied.
  public string buildWhereClause(
    String whereString,
    String objectName,
    String fieldName,
    String queryParameter,
    String soqlQuery,
    String recordType
  ) {
    Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
    SObjectType myObj = schemaMap.get(objectName);
    SObjectField myField = myObj.getDescribe().fields.getMap().get(fieldName);
    String myFieldType = String.valueOf(myField.getDescribe().getSoapType());
    if (myFieldType != 'String' && recordType != null) {
      return whereString +
        fieldName +
        queryParameter +
        String.valueof(soqlQuery) +
        ' AND RecordType.DeveloperName = ' +
        '\'' +
        String.escapeSingleQuotes(recordType) +
        '\' ';
    }
    if (myFieldType != 'String' && recordType == null) {
      return whereString +
        fieldName +
        queryParameter +
        String.valueof(soqlQuery);
    }
    if (myFieldType == 'String' && recordType != null) {
      return whereString +
        fieldName +
        queryParameter +
        '\'' +
        String.escapeSingleQuotes(soqlQuery) +
        '\' ' +
        ' AND RecordType.DeveloperName = ' +
        '\'' +
        String.escapeSingleQuotes(recordType) +
        '\' ';
    }
    if (myFieldType == 'String' && recordType == null) {
      return whereString +
        fieldName +
        queryParameter +
        '\'' +
        String.escapeSingleQuotes(soqlQuery) +
        '\' ';
    } else {
      return null;
    }
  }
  List<SObject> recordsToBeReassigned = new List<SObject>();
  public List<SObject> getRecordsToBeReassigned(List<SObject> queryResult) {
    /*
    Looping through the OOO Records. If the OOO Requestor equals the records to be re-assigned,
     the loop updates each record with the backup owner Id from the original OOO record.
     */
    for (OutOfOfficeRequest_OOOR__c oooRecord : [
      SELECT Id, BackupUser_OOOR__c, PersonTakingTimeOff_OOOR__c, Status_OOOR__c
      FROM OutOfOfficeRequest_OOOR__c
      WHERE
        StartDate_OOOR__c <= TODAY
        AND EndDate_OOOR__c >= TODAY
        AND Status_OOOR__c = 'Approved'
    ]) {
      for (Sobject objectToBeInserted : queryResult) {
        // This if statement is needed to make sure that multiple OOO records aren't conflicing with each other.
        if (
          objectToBeInserted.get('OwnerId') ==
          oooRecord.PersonTakingTimeOff_OOOR__c
        ) {
          objectToBeInserted.put('OwnerId', oooRecord.BackupUser_OOOR__c);
          recordsToBeReassigned.add(objectToBeInserted);
        }
      }
    }
    return recordsToBeReassigned;
  }

  List<SObject> feeditemsToBeUpdated = new List<SObject>();

  public List<SObject> getFeedPosts(
    List<SObject> recordsToBeUpdated,
    List<OutOfTheOfficeSettings_OOOR__mdt> metadataQuerySettings
  ) {
    for (SObject recordToBeUpdated : recordsToBeUpdated) {
      for (
        OutOfTheOfficeSettings_OOOR__mdt metadataQuerySetting : metadataQuerySettings
      ) {
        if (
          // Need this if statement to make sure that every record gets updated by only the corresponding MDT record
          metadataQuerySetting.FeedPost_OOOR__c == true &&
          recordToBeUpdated.getSObjectType().getDescribe().getName() ==
          metadataQuerySetting.ObjectAPIName_OOOR__c &&
          recordToBeUpdated.getSObjectType().getDescribe().isFeedEnabled()
        ) {
          FeedItem fi = new FeedItem(
            ParentId = recordToBeUpdated.Id,
            Body = metadataQuerySetting.FeedPostMessage_OOOR__c,
            Type = 'TextPost'
          );
          feeditemsToBeUpdated.add(fi);
        }
      }
    }
    return feeditemsToBeUpdated;
  }
}